// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server-response.proto

#include "server-response.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace busboy {
namespace api {
class BusBoyResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<BusBoyResponse>
      _instance;
} _BusBoyResponse_default_instance_;
}  // namespace api
}  // namespace busboy
namespace protobuf_server_2dresponse_2eproto {
static void InitDefaultsBusBoyResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::busboy::api::_BusBoyResponse_default_instance_;
    new (ptr) ::busboy::api::BusBoyResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::busboy::api::BusBoyResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_BusBoyResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsBusBoyResponse}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_BusBoyResponse.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::busboy::api::BusBoyResponse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::busboy::api::BusBoyResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::busboy::api::BusBoyResponse, time_),
  0,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 6, sizeof(::busboy::api::BusBoyResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::busboy::api::_BusBoyResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "server-response.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\025server-response.proto\022\nbusboy.api\"\036\n\016B"
      "usBoyResponse\022\014\n\004time\030\001 \001(\004B%\n!com.jonki"
      "mbel.busboybackend.protoP\001"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 106);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "server-response.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_server_2dresponse_2eproto
namespace busboy {
namespace api {

// ===================================================================

void BusBoyResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BusBoyResponse::kTimeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BusBoyResponse::BusBoyResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_server_2dresponse_2eproto::scc_info_BusBoyResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:busboy.api.BusBoyResponse)
}
BusBoyResponse::BusBoyResponse(const BusBoyResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  time_ = from.time_;
  // @@protoc_insertion_point(copy_constructor:busboy.api.BusBoyResponse)
}

void BusBoyResponse::SharedCtor() {
  time_ = GOOGLE_ULONGLONG(0);
}

BusBoyResponse::~BusBoyResponse() {
  // @@protoc_insertion_point(destructor:busboy.api.BusBoyResponse)
  SharedDtor();
}

void BusBoyResponse::SharedDtor() {
}

void BusBoyResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* BusBoyResponse::descriptor() {
  ::protobuf_server_2dresponse_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_server_2dresponse_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const BusBoyResponse& BusBoyResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_server_2dresponse_2eproto::scc_info_BusBoyResponse.base);
  return *internal_default_instance();
}


void BusBoyResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:busboy.api.BusBoyResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  time_ = GOOGLE_ULONGLONG(0);
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool BusBoyResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:busboy.api.BusBoyResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint64 time = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_time();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &time_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:busboy.api.BusBoyResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:busboy.api.BusBoyResponse)
  return false;
#undef DO_
}

void BusBoyResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:busboy.api.BusBoyResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint64 time = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->time(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:busboy.api.BusBoyResponse)
}

::google::protobuf::uint8* BusBoyResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:busboy.api.BusBoyResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint64 time = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->time(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:busboy.api.BusBoyResponse)
  return target;
}

size_t BusBoyResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:busboy.api.BusBoyResponse)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // optional uint64 time = 1;
  if (has_time()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->time());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BusBoyResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:busboy.api.BusBoyResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const BusBoyResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const BusBoyResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:busboy.api.BusBoyResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:busboy.api.BusBoyResponse)
    MergeFrom(*source);
  }
}

void BusBoyResponse::MergeFrom(const BusBoyResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:busboy.api.BusBoyResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_time()) {
    set_time(from.time());
  }
}

void BusBoyResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:busboy.api.BusBoyResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BusBoyResponse::CopyFrom(const BusBoyResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:busboy.api.BusBoyResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BusBoyResponse::IsInitialized() const {
  return true;
}

void BusBoyResponse::Swap(BusBoyResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BusBoyResponse::InternalSwap(BusBoyResponse* other) {
  using std::swap;
  swap(time_, other->time_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata BusBoyResponse::GetMetadata() const {
  protobuf_server_2dresponse_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_server_2dresponse_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace api
}  // namespace busboy
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::busboy::api::BusBoyResponse* Arena::CreateMaybeMessage< ::busboy::api::BusBoyResponse >(Arena* arena) {
  return Arena::CreateInternal< ::busboy::api::BusBoyResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
