// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server-response.proto

#ifndef PROTOBUF_INCLUDED_server_2dresponse_2eproto
#define PROTOBUF_INCLUDED_server_2dresponse_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_server_2dresponse_2eproto 

namespace protobuf_server_2dresponse_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_server_2dresponse_2eproto
namespace busboy {
namespace api {
class BusBoyResponse;
class BusBoyResponseDefaultTypeInternal;
extern BusBoyResponseDefaultTypeInternal _BusBoyResponse_default_instance_;
}  // namespace api
}  // namespace busboy
namespace google {
namespace protobuf {
template<> ::busboy::api::BusBoyResponse* Arena::CreateMaybeMessage<::busboy::api::BusBoyResponse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace busboy {
namespace api {

// ===================================================================

class BusBoyResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:busboy.api.BusBoyResponse) */ {
 public:
  BusBoyResponse();
  virtual ~BusBoyResponse();

  BusBoyResponse(const BusBoyResponse& from);

  inline BusBoyResponse& operator=(const BusBoyResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BusBoyResponse(BusBoyResponse&& from) noexcept
    : BusBoyResponse() {
    *this = ::std::move(from);
  }

  inline BusBoyResponse& operator=(BusBoyResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BusBoyResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BusBoyResponse* internal_default_instance() {
    return reinterpret_cast<const BusBoyResponse*>(
               &_BusBoyResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(BusBoyResponse* other);
  friend void swap(BusBoyResponse& a, BusBoyResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BusBoyResponse* New() const final {
    return CreateMaybeMessage<BusBoyResponse>(NULL);
  }

  BusBoyResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BusBoyResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BusBoyResponse& from);
  void MergeFrom(const BusBoyResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BusBoyResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 time = 1;
  bool has_time() const;
  void clear_time();
  static const int kTimeFieldNumber = 1;
  ::google::protobuf::uint64 time() const;
  void set_time(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:busboy.api.BusBoyResponse)
 private:
  void set_has_time();
  void clear_has_time();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint64 time_;
  friend struct ::protobuf_server_2dresponse_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BusBoyResponse

// optional uint64 time = 1;
inline bool BusBoyResponse::has_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BusBoyResponse::set_has_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BusBoyResponse::clear_has_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BusBoyResponse::clear_time() {
  time_ = GOOGLE_ULONGLONG(0);
  clear_has_time();
}
inline ::google::protobuf::uint64 BusBoyResponse::time() const {
  // @@protoc_insertion_point(field_get:busboy.api.BusBoyResponse.time)
  return time_;
}
inline void BusBoyResponse::set_time(::google::protobuf::uint64 value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:busboy.api.BusBoyResponse.time)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace api
}  // namespace busboy

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_server_2dresponse_2eproto
