/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 at Thu Jan 17 20:30:56 2019. */

#ifndef PB_BUSBOY_API_BUS_BOY_PB_H_INCLUDED
#define PB_BUSBOY_API_BUS_BOY_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _busboy_api_ColorScheme {
    busboy_api_ColorScheme_SEAHAWKS = 0,
    busboy_api_ColorScheme_RAINBOW = 1,
    busboy_api_ColorScheme_SPRING = 2,
    busboy_api_ColorScheme_SUMMER = 3,
    busboy_api_ColorScheme_FALL = 4,
    busboy_api_ColorScheme_WINTER = 5
} busboy_api_ColorScheme;
#define _busboy_api_ColorScheme_MIN busboy_api_ColorScheme_SEAHAWKS
#define _busboy_api_ColorScheme_MAX busboy_api_ColorScheme_WINTER
#define _busboy_api_ColorScheme_ARRAYSIZE ((busboy_api_ColorScheme)(busboy_api_ColorScheme_WINTER+1))

/* Struct definitions */
typedef struct _busboy_api_Route {
    pb_callback_t short_name;
    pb_callback_t headsign;
/* @@protoc_insertion_point(struct:busboy_api_Route) */
} busboy_api_Route;

typedef struct _busboy_api_Arrival {
    bool has_route_index;
    uint32_t route_index;
    bool has_ms_to_arrival;
    uint32_t ms_to_arrival;
    bool has_predicted;
    bool predicted;
/* @@protoc_insertion_point(struct:busboy_api_Arrival) */
} busboy_api_Arrival;

typedef struct _busboy_api_DisplayedTime {
    bool has_ms_since_epoch;
    uint64_t ms_since_epoch;
    bool has_daylight_savings_time;
    bool daylight_savings_time;
/* @@protoc_insertion_point(struct:busboy_api_DisplayedTime) */
} busboy_api_DisplayedTime;

typedef struct _busboy_api_TimeFrame {
    bool has_start_time_ms_since_epoch;
    uint64_t start_time_ms_since_epoch;
    bool has_end_time_ms_since_epoch;
    uint64_t end_time_ms_since_epoch;
/* @@protoc_insertion_point(struct:busboy_api_TimeFrame) */
} busboy_api_TimeFrame;

typedef struct _busboy_api_Response {
    bool has_time;
    busboy_api_DisplayedTime time;
    pb_callback_t arrivals;
    pb_callback_t routes;
    pb_callback_t temporary_message;
    pb_callback_t temporary_style;
/* @@protoc_insertion_point(struct:busboy_api_Response) */
} busboy_api_Response;

typedef struct _busboy_api_TemporaryMessage {
    bool has_time_frame;
    busboy_api_TimeFrame time_frame;
    pb_callback_t message;
    bool has_color_scheme_override;
    busboy_api_ColorScheme color_scheme_override;
/* @@protoc_insertion_point(struct:busboy_api_TemporaryMessage) */
} busboy_api_TemporaryMessage;

typedef struct _busboy_api_TemporaryStyle {
    bool has_time_frame;
    busboy_api_TimeFrame time_frame;
    bool has_color_scheme_override;
    busboy_api_ColorScheme color_scheme_override;
/* @@protoc_insertion_point(struct:busboy_api_TemporaryStyle) */
} busboy_api_TemporaryStyle;

/* Default values for struct fields */

/* Initializer values for message structs */
#define busboy_api_Response_init_default         {false, busboy_api_DisplayedTime_init_default, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define busboy_api_DisplayedTime_init_default    {false, 0, false, 0}
#define busboy_api_Arrival_init_default          {false, 0, false, 0, false, 0}
#define busboy_api_Route_init_default            {{{NULL}, NULL}, {{NULL}, NULL}}
#define busboy_api_TemporaryMessage_init_default {false, busboy_api_TimeFrame_init_default, {{NULL}, NULL}, false, _busboy_api_ColorScheme_MIN}
#define busboy_api_TemporaryStyle_init_default   {false, busboy_api_TimeFrame_init_default, false, _busboy_api_ColorScheme_MIN}
#define busboy_api_TimeFrame_init_default        {false, 0, false, 0}
#define busboy_api_Response_init_zero            {false, busboy_api_DisplayedTime_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define busboy_api_DisplayedTime_init_zero       {false, 0, false, 0}
#define busboy_api_Arrival_init_zero             {false, 0, false, 0, false, 0}
#define busboy_api_Route_init_zero               {{{NULL}, NULL}, {{NULL}, NULL}}
#define busboy_api_TemporaryMessage_init_zero    {false, busboy_api_TimeFrame_init_zero, {{NULL}, NULL}, false, _busboy_api_ColorScheme_MIN}
#define busboy_api_TemporaryStyle_init_zero      {false, busboy_api_TimeFrame_init_zero, false, _busboy_api_ColorScheme_MIN}
#define busboy_api_TimeFrame_init_zero           {false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define busboy_api_Route_short_name_tag          1
#define busboy_api_Route_headsign_tag            2
#define busboy_api_Arrival_route_index_tag       1
#define busboy_api_Arrival_ms_to_arrival_tag     2
#define busboy_api_Arrival_predicted_tag         3
#define busboy_api_DisplayedTime_ms_since_epoch_tag 1
#define busboy_api_DisplayedTime_daylight_savings_time_tag 2
#define busboy_api_TimeFrame_start_time_ms_since_epoch_tag 1
#define busboy_api_TimeFrame_end_time_ms_since_epoch_tag 2
#define busboy_api_Response_time_tag             1
#define busboy_api_Response_arrivals_tag         2
#define busboy_api_Response_routes_tag           3
#define busboy_api_Response_temporary_message_tag 4
#define busboy_api_Response_temporary_style_tag  5
#define busboy_api_TemporaryMessage_time_frame_tag 1
#define busboy_api_TemporaryMessage_message_tag  2
#define busboy_api_TemporaryMessage_color_scheme_override_tag 3
#define busboy_api_TemporaryStyle_time_frame_tag 1
#define busboy_api_TemporaryStyle_color_scheme_override_tag 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t busboy_api_Response_fields[6];
extern const pb_field_t busboy_api_DisplayedTime_fields[3];
extern const pb_field_t busboy_api_Arrival_fields[4];
extern const pb_field_t busboy_api_Route_fields[3];
extern const pb_field_t busboy_api_TemporaryMessage_fields[4];
extern const pb_field_t busboy_api_TemporaryStyle_fields[3];
extern const pb_field_t busboy_api_TimeFrame_fields[3];

/* Maximum encoded size of messages (where known) */
/* busboy_api_Response_size depends on runtime parameters */
#define busboy_api_DisplayedTime_size            13
#define busboy_api_Arrival_size                  14
/* busboy_api_Route_size depends on runtime parameters */
/* busboy_api_TemporaryMessage_size depends on runtime parameters */
#define busboy_api_TemporaryStyle_size           26
#define busboy_api_TimeFrame_size                22

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define BUS_BOY_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
