// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server-response.proto

package com.jonkimbel.busboybackend.proto;

public interface BusBoyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:busboy.api.BusBoyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 time = 1;</code>
   */
  boolean hasTime();
  /**
   * <code>optional uint64 time = 1;</code>
   */
  long getTime();
}
